<a href="https://colab.research.google.com/github/liduthomas/genesis/blob/master/Lidiya_Thomas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

imported python lib.

In [ ]:
import pandas as pd
import numpy as np

in the next step, I have imported the iris dataset and the load_iris function will give a bunch of iris data set which we are storing inside iris_dataset.

In [ ]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()



Here we are printing keys of iris_dataset

In [ ]:
print('keys of iris_dataset:\n{}'.format(iris_dataset.keys()))


keys of iris_dataset:
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Here we are  printing description of iris_dataset

In [ ]:
print(iris_dataset['DESCR'][:193]+"\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


Here we are printing target_names of iris_dataset

In [ ]:
print('Target name:\n {}'.format(iris_dataset['target_names']))

Target name:
 ['setosa' 'versicolor' 'virginica']


Here we are printing feature_names of iris_dataset

In [ ]:
print('Feature name:\n {}'.format(iris_dataset['feature_names']))

Feature name:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Here we are printing type of iris_dataset['data']

In [ ]:
print('Type of data\n {}'.format(type(iris_dataset['data'])))

Type of data
 <class 'numpy.ndarray'>


The shape of an array is the number of elements in each dimension.
Here we are printing the shape of iris_dataset['data']

In [ ]:
print('shape of data:{}'.format(iris_dataset['data'].shape))

shape of data:(150, 4)


To print the  first five rows of iris_dataset

In [ ]:
print('First Five rows of data:\n {}',format(iris_dataset['data'][:5]))

First Five rows of data:
 {} [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Here we are printing type of iris_dataset['target']

In [ ]:
print('type of Target:\n {}'.format(type(iris_dataset['target'])))

type of Target:
 <class 'numpy.ndarray'>


Here we are printing shape of iris_dataset['target']

In [ ]:
print('shape of Target:\n {}'.format(iris_dataset['target'].shape))

shape of Target:
 (150,)


To print iris_dataset['target']

In [ ]:
print('Target:\n {}'.format(iris_dataset['target']))

Target:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


train_test_split will Split arrays or matrices into the random train and test subsets.

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

Printing shape of X_tain,y_train,X_test,X_test.


In [ ]:
print('X_train of data:{}'.format(X_train.shape))
print('y_train of data:{}'.format(y_train.shape))
print('X_test of data:{}'.format(X_test.shape))
print('y_test of data:{}'.format(y_test.shape))

X_train of data:(112, 4)
y_train of data:(112,)
X_test of data:(38, 4)
y_test of data:(38,)


The K in the name of this classifier represents the k nearest neighbors, where k is an integer value specified by the user.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

fit an estimator to be able to predict the classes to which the unseen samples belong.

In [ ]:
knn.fit(X_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

printing shape of X_new

In [ ]:
X_new=np.array([[5,2.9,1,0.2]])
print('X_new.shape {}'.format(X_new.shape))

X_new.shape (1, 4)


Making predictions with X_new

In [ ]:
prediction=knn.predict(X_new)
print('Prediction: {} '.format(prediction))
print('Predicted target name: {} '.format(iris_dataset['target_names'][prediction]))

Prediction: [0] 
Predicted target name: ['setosa'] 


Making predictions with X_test

In [ ]:
y_pred=knn.predict(X_test)
print('Test set Prediction: {} '.format(y_pred))

Test set Prediction: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2] 


Calculating mean value of predictions.

In [ ]:
print('Test Set Score: {} '.format(np.mean(y_pred==y_test)))

Test Set Score: 0.9736842105263158 
